helloghz/helloghz/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()




urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Hello2.views.home', name='home'),
    # url(r'^Hello2/', include('Hello2.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),

    #/map/ basicaly the index of the site
    url(r'^', include('map.urls')),

)

helloghz/map/urls.py
from django.conf.urls import patterns, url

from map import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'sayhello/$', views.sayhello, name='sayhello'),
    url(r'videopopup/$', views.videopopup, name='videopopup'),
    url(r'videos/$', views.videos, name='videos'),

)

helloghz/map/models.py
from django.db import models

# Create your models here.
class Point(models.Model):
    vid = models.CharField(max_length=20)
    lat = models.FloatField()
    long = models.FloatField()
    #vTitle = models.CharField(max_length=120)
    #vDescription = models.CharField(max_length=5000)
    #saving these for when I'm not too lazy to Regex
    #vYoutubeDate = models.DateTimeField()
    #vHelloDate = models.DateTimeField()

helloghz/map/forms.py
from django import forms

class helloForm(forms.Form):
    full_url = forms.URLField(required=True,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    lat = forms.FloatField(required=True)
    long = forms.FloatField(required=True)
    #vTitle = forms.CharField(max_length=120)
    #vDescription = forms.CharField(max_length=5000)
    address = forms.CharField(max_length=100,
                              required=True,
                              initial="Salt Lake City, UT",
                              widget=forms.TextInput(attrs={"class": "form-control"})

    )

helloghz/map/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import render
from map.models import Point
from map.forms import helloForm
from urlparse import urlparse
from django.http import HttpResponse
from django.views.decorators.clickjacking import xframe_options_exempt


#############FOR old vs new parse_qs Versions##########
import urlparse # if we're pre-2.6, this will not include parse_qs
try:
    from urlparse import parse_qs
    from urlparse import urlparse
except ImportError: # old version, grab it from cgi
    from cgi import parse_qs
    urlparse.parse_qs = parse_qs
    urlparse.urlparse = urlparse




#index just returns list of points for javascript to map
def index(request):
    returnlist = Point.objects.all().order_by("-id")
    context = {'returnlist': returnlist}

    return render(request, 'map/index.html', context)

#videopopup used in an iframe popup from the map click
def videopopup(request):
    videoIds = request.GET.get('v','')

    returnlist = videoIds.split(',');
    context = {'returnlist': returnlist}

    return render(request, 'map/videopopup.html', context)

#videos for teh stats and semi raw data
def videos(request):
    fulllist = Point.objects.all().order_by("-id")
    context = {'fulllist': fulllist}

    return render(request, 'map/videos.html', context)

#Lets users add a video to the database to be mapped
@xframe_options_exempt
def sayhello(request):

    if request.method == 'POST': # If the form has been submitted...
        form = helloForm(request.POST) # A form bound to the POST data
        if canPostData(request.POST): # All validation rules pass
            form.is_valid()#Testing if required for cleaned_data
            videoId = getVideoId(form.cleaned_data['full_url'])

            newPoint = Point(vid=videoId, lat=form.cleaned_data['lat'], long=form.cleaned_data['long'])

            newPoint.save()
            # ...
            return HttpResponseRedirect('/') # Redirect after POST
    else:
        form = helloForm() # An unbound form

    return render(request, 'map/sayhello.html', {
        'form': form,
    })

def getVideoId(fullUrl):
    """
    returns video id when given a youtube url
    Examples:
    - http://youtu.be/SA2iWivDJiE
    - http://www.youtube.com/watch?v=_oPAwA_Udwc&feature=feedu
    - http://www.youtube.com/embed/SA2iWivDJiE
    - http://www.youtube.com/v/SA2iWivDJiE?version=3&amp;hl=en_US
    """
    query = urlparse(fullUrl)
    if query.hostname == 'youtu.be':
        return query.path[1:]
    if query.hostname in ('www.youtube.com', 'youtube.com'):
        if query.path == '/watch':
            p = parse_qs(query.query)
            return p['v'][0]
        if query.path[:7] == '/embed/':
            return query.path.split('/')[2]
        if query.path[:3] == '/v/':
            return query.path.split('/')[2]
    # fail?
    return None

def canPostData(postedData):
    form = helloForm(postedData)
    if not form.is_valid():
        return False
    videoId = str(getVideoId(form.cleaned_data['full_url']))
    if videoId is None:
        return False

    return True

helloghz/map/templates/map/baselayout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />{% load staticfiles %}
    <title>{% block title %}The Hello Geekahertz Project{% endblock %}</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href='{% static "map/css/magnific-popup.css" %}'>
    <link rel="stylesheet" href='{% static "map/css/site.css" %}' />


</head>

<body>
{% block menubar %}
   
{% endblock %}

   {% block body %}{% endblock %}
    



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <!-- Magnific Popup core JS file -->
    <script src="{% static "map/scripts/jquery.magnific-popup.js" %}"></script>
    <script src='{% static "map/scripts/page.js" %}'></script>

{% block scripts %}

{% endblock %}
</body>


</html>

helloghz/map/templates/map/clownpenis.html
{% extends "map/layout.html" %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2> Teh stats and shit murica</h2>
        </div>
    </div>

    <div class="row ">

        <div class="col-md-12">{% if fulllist %}
            <div>Total videos: {{fulllist.count}}</div>
            <div>
                Most Recent Upload: {%with fulllist|first as last%}<a class='video' href='http://www.youtube.com/watch?v={{last.vid}}'><img class='img-responsive' src='http://img.youtube.com/vi/{{last.vid}}/1.jpg'></a>{% endwith %}
            </div>{% for point in fulllist %}
            <div class='video-thumb'>
                <a class='video' href='http://www.youtube.com/watch?v={{point.vid}}'><img class='img-responsive' src='http://img.youtube.com/vi/{{point.vid}}/1.jpg'></a>
            </div>{% endfor %}

{% endif %}

        </div>


    </div>

</div>
{% endblock %}

{% block scripts %}

{% endblock %}

helloghz/map/templates/map/index.html
{% extends "map/layout.html" %}{% load staticfiles %}

{% block content %}

<div class="jumbotron ">

    <div class="row">

        <div class="col-md-3  ">
            <div>
                <img class="img-responsive" src='{% static "map/images/logo3.png" %}' alt="Hello Geekahertz" align="center">
            </div>
        </div>
        <div class="col-md-9">
            <h4>The Hello Geekahertz Project</h4>
            <p style="font-size: 12pt">
                The goal of this project is to get as many of our friends <b>(thats you!)</b> as we can to record “hello
                geekahertz” videos around the world.
            </p>
            <p style="font-size: 12pt">
                We will take care of the rest by organizing these videos and their corresponding locations in an easy to view
                format on this web site.
            </p>


            <div class="text-right">
                <button class="btn btn-lg btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg"><span class="glyphicon glyphicon-info-sign"></span> Help Me</button>
                <a href="/sayhello" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-pushpin"></span> Say Hello</a>
            </div>
        </div>

    </div>

</div>




<div id="map-canvas" class="jumbotron"> </div>
<div id="divError"></div>





<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header ">


                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title " id="mySmallModalLabel">Saying Hello and Shirt Things</h4>

            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <h2><span class="glyphicon glyphicon-facetime-video"></span> Record</h2>
                        Record a video by saying "hello geekahertz" at any point in video.
                    </div>
                    <div class="col-md-4">
                        <h2><span class="glyphicon glyphicon-cloud-upload"></span> Upload</h2>
                        Upload your video to your YouTube account.
                    </div>
                    <div class="col-md-4">
                        <h2><span class="glyphicon glyphicon-pushpin"></span> Say Hello</h2>
                        <a class="active" href="/sayhello"><strong>Say Hello</strong></a> by giving us the YouTube URL and location the video was recorded.
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <a href="/sayhello" class="btn btn-md btn-success"><span class="glyphicon glyphicon-pushpin"></span> Say Hello</a>
                <button type="button" class="btn btn-default btn-md" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Close</button>

            </div>
        </div>
    </div>
</div>


<a class="video-popup" id="popuplink" title="videos from the area">

</a>
{% endblock %}


{% block scripts %}

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9fe7fwW2cd7dCFqr65ePzn6xOKzJCGCM&sensor=false">
</script>
<script type="text/javascript">
    $(document).ready(function () {
        google.maps.event.addDomListener(window, 'load', initialize);
    });

    function initialize() {
        var mapOptions = {
            center: new google.maps.LatLng(0, 0),
            zoom: 2,
            scaleControl: true
        };
        var divMapCanvas = $("#map-canvas")[0];
        var map = new google.maps.Map(divMapCanvas, mapOptions);

        var myLatlng = new google.maps.LatLng(-25.363882, 131.044922);
        var marker = new google.maps.Marker({ position: myLatlng});

        // To add the marker to the map, call setMap();
        //marker.setMap(map);

        {% if returnlist %}
            {% for point in returnlist %}
                myLatlng = new google.maps.LatLng({{point.lat}}, {{point.long}} );
                marker = new google.maps.Marker({ position: myLatlng});


          google.maps.event.addListener(marker, "click", function () {
	//Justin, I guess you get you replace this infowindow with some fancy magic. the "nearbyMarkers" function will return an array of video ids
	//I had the infowindow display the array list just so I knew it was working
	var markers = nearbyMarkers({{point.lat}}, {{point.long}}, map.getZoom()).toString();
    $('#popuplink').attr("href", '/map/videopopup/?v='+markers);
    $('#popuplink').attr("title", 'videos and shit');
    $('#popuplink').click();
    /*
     $.magnificPopup.open({
  items: {
    src: '/map/videopopup/?v='+markers
  },
  type: 'iframe',
    gallery: {
            enabled: true
        }
});*/
	

});

marker.setMap(map);


            {% endfor %}
            {% else %}
         $(".divError").show();
        {% endif %}
    }

    //Takes a lat, long, and a map zoom level
    //returns an array of video ids near that lat,long scaled based on the maps zoom level
    //Instead of doing it 'right' makes a  box around the point instead of a circle
    function nearbyMarkers(lat, long, zoomlevel) {
        var pointList = [];//there has to be a better way but I'm going ghetto mutli dimensional array
        var result = [];

        //rough decimal degree delta for 1 kilometer
        var kmLat = 0.008983;
        var kmLong = 0.015060;


        //calculate how much to scale based on zoom level. Maps api says furthest out zoom is 0, most zoomed is 21
        //each change in zoom level doubles, or halves the zoom
        //so this gets ugly fast. if we want a box roughly .5 by .5 meters at zoom 21 our box needs to be 1048.576 by 1048.576 meters at zoom 0
        //This means that our scale off of max zoom (1048.576) should be 1/(2^zoomlevel)
        var scale = 1 / (Math.pow(2,zoomlevel));

        //scale our lat and long deltas
        var latDelta = scale * 1048.576 * kmLat;
        var longDelta = scale * 1048.576 * kmLong;

        //create our lat/long box bounds
        var leftBound = lat - latDelta;
        var rightBound = lat + latDelta;
        var topBound = long + longDelta;
        var bottomBound = long - longDelta;

        //populate the ghetto multi dimensional array the the point values
        {% if returnlist %}
            {% for point in returnlist %}
                pointList[{{forloop.counter0}}] = [{{point.lat}}, {{point.long}}, '{{point.vid}}'];
            {% endfor %}
        {% else %}
            $(".divError").show();
        {% endif %}


        //check all points to see if they fit in the box
        for (var i=0;i<pointList.length;i++)
        {
            //check to see if lat fits within the X bounds
            if(pointList[i][0] > leftBound && pointList[i][0] < rightBound){
                //check to see if the long fits within the Y bounds
                if(pointList[i][1] > bottomBound && pointList[i][1] < topBound){
                    //if I fits I sits
                    result.push(pointList[i][2]);
                 }
            }
        }
        //this is just for troubleshooting scale. not needed
        //result.push('  meters: '+ ((longDelta/kmLong)*1000).toString() + '  kilometers: '+ ((longDelta/kmLong)).toString()) +'"';

        return result;
    }


</script>
{% endblock %}

helloghz/map/templates/map/layout.html
{% extends "map/baselayout.html" %}


{% block menubar %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>


                </button>
                <div class="logo" style=" margin:00px 0px 0px 0px ">
                    <a class="navbar-brand" href="/">
                        Hello Geekahertz &lt;g&gt;
                    </a>


                </div>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">

                    <li><a href="/sayhello"><span class="glyphicon glyphicon-pushpin"></span> Say Hello</a></li>
                    <li><a href="/videos"><span class="glyphicon glyphicon-facetime-video"></span> Videos</a></li>


                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>

{% endblock %}

    {% block body %}<div class="container">{% block content %}{% endblock %}</div>{% endblock %}




  

{% block scripts %}

{% endblock %}

helloghz/map/templates/map/sayhello.html
{% extends "map/layout.html" %}

{% block content %}

<!--This script disables form submission on enter key and instead triggers the map search function-->
<!--If we ever have need for enter keys on this page this script will need to be more selective-->
<script language=javascript type=text/javascript>

function stopRKey(evt) {
   var evt = (evt) ? evt : ((event) ? event : null);
   var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
   if ((evt.keyCode == 13) && (node.type=="text")) {showAddress($("#id_address").val(),true); return false;}
}

document.onkeypress = stopRKey;

</script>
<form action="/map/sayhello/" method="post" >{% csrf_token %}{{ form.non_field_errors }}
    <div>
        <div style="padding: 10px 0 10px 0">
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary btn-md"> <span class="glyphicon glyphicon-pushpin"></span> Save</button>
                    <button type="submit" class="btn btn-default btn-md">  Cancel</button>
                </div>
            </div>
        </div>
        <div class="panel panel-default" style="width: 100%; margin: auto">
            <div class="panel-heading">

                <h3 class="panel-title">Tell us about your video</h3>



            </div>
            <div class="panel-body" style="padding: 15px;">

                <div class="row">
                    <div class="col-md-6">

                        <label for="id_full_url" class="control-label">YouTube URL</label>{{ form.full_url }}
{{ form.full_url.errors }}
                        <span class="help-block">
                            <small>E.g. http://www.youtube.com/watch?v=oHg5SJYRHA0 </small>
                        </span>

                        <div id="divVideo"></div>
                    </div>
                    <div class="col-md-6">

                        <label for="id_address" class="control-label"> Video Location</label>

                        <div class="input-group">{{ form.address }}
                            <span class="input-group-btn">
                                <button id="btnSearch" type="button" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-search"></span> Search
                                </button>
                            </span>
                        </div>

                        <span class="help-block"><small>Search for an address then drag the marker below to adjust the location.</small></span>



                        <div id="map-canvas" class="jumbotron" />



                    </div>
                </div>
                <div class="fieldWrapper form-group">

                </div>
                <div class="fieldWrapper form-group">

                </div>
                <div style="visibility: hidden">
                    <div class="fieldWrapper">{{ form.lat }}
                    </div>
                    <div class="fieldWrapper ">{{ form.long }}
                    </div>
                    <div class="fieldWrapper">{{ form.vTitle }}
                    </div>
                    <div class="fieldWrapper ">{{ form.vDescription }}
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div style="margin: 10px 0px">


    </div>

</form>

{% endblock %}

{% block scripts %}
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAjU0EJWnWPMv7oQ-jjS7dYxSPW5CJgpdgO_s4yyMovOaVh_KvvhSfpvagV18eOyDWu7VytS6Bi1CWxw"
        type="text/javascript"></script>
<script type="text/javascript">

    $(function () {


        var map = null;
        var geocoder = null;
        initialize();
        showAddress($("#id_address").val());

        $(window).unload(function () {
            GUnload();
        });

        $("#btnSearch").click(function (e) {

            showAddress($("#id_address").val());
        });

        $("#id_full_url").change(function () {
            var videoId = youtube_parser($(this).val());
            updateMapFromVid(videoId); //uses vidData global variable to "pass" values back
            //preSubmit(videoId); //testing
              //alert(vidData.title);
              //alert(vidData.description);
              //alert(vidData.day);
              //alert(vidData.lat);
              //alert(vidData.long);

            $("#divVideo").html("<iframe width='100%' height='315' src='//www.youtube.com/embed/" + videoId + "' frameborder='0' allowfullscreen></iframe>");

        });


    });

    function youtube_parser(url) {
        var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
        var match = url.match(regExp);
        if (match && match[2].length == 11) {
            return match[2];
        } else {
            alert("Your video is broke");
            enableFormElement('id_address');
            enableFormElement('btnSearch');
        }
    }
    //kept for later reference when adding titles, dates, etc
    function tempForLater(videoId) {
        //This is an aysnc function. It does ugly things if you expect it to run inline
        $.getJSON('https://www.googleapis.com/youtube/v3/videos?part=snippet%2CrecordingDetails&id=' +videoId+ '&key=AIzaSyC5uDjEOvf_uKgsD-Gbzp-DlhWPSGsdsS0',function(data,snippet){+
            $.each(data.items, function(index, items) {

                  vidData = {
                    title: items.snippet.title,
                    description: items.snippet.description,
                    //Saving for when I'm not too lazy to regex
                    //day: items.snippet.publishedAt,
                    //month: '',
                    //year: '',
                    //hour: '',
                    lat: items.recordingDetails.location.latitude,
                    long: items.recordingDetails.location.longitude


                  };

            });
        });

    }
    //for future use
    function preSubmit(vidData) {
        if(vidData.lat != '' && vidData.long != '')
            {
                var address = vidData.lat + ',' + vidData.long;
                showAddress(address,false);
            }
        else
            {
                showAddress('salt lake city, ut',true); //I don't like this but can't seem to pull document values
            }
        var textbox = document.getElementsByName('vTitle')[0]
        textbox.value = vidData.title;
        var textbox = document.getElementsByName('vDescription')[0]
        textbox.value = vidData.description;

    }

        function updateMapFromVid(videoId) {
        //This is an aysnc function. It does ugly things if you expect it to run inline
        $.getJSON('https://www.googleapis.com/youtube/v3/videos?part=snippet%2CrecordingDetails&id=' +videoId+ '&key=AIzaSyC5uDjEOvf_uKgsD-Gbzp-DlhWPSGsdsS0',function(data,snippet){+
            $.each(data.items, function(index, items) {
                  if(items.recordingDetails){
                      var vidData = {
                        lat: items.recordingDetails.location.latitude,
                        long: items.recordingDetails.location.longitude
                      };
                  }
                  else{
                      var vidData = {
                        lat: '',
                        long: ''
                      };
                  }

                    if(vidData.lat != '' && vidData.long != '')
                        {
                            var address = vidData.lat + ',' + vidData.long;
                            showAddress(address,false);

                            disableFormElement('id_address');
                            disableFormElement('btnSearch');
                        }
                    else
                        {
                            enableFormElement('id_address');
                            enableFormElement('btnSearch');
                        }

            });
        });

    }

    function disableFormElement(elementID){
        if (document.getElementById(elementID).type == 'button'){

            document.getElementById(elementID).disabled = true;
        }
        else {
            document.getElementById(elementID).setAttribute('readonly','readonly');
        }
    }

    function enableFormElement(elementID){
        if (document.getElementById(elementID).type == 'button'){
            document.getElementById(elementID).disabled = false;
        }
        else{
            document.getElementById(elementID).removeAttribute('readonly');
        }
    }


    function updateMapFromAddressBar(){

        showAddress(document.getElementById('id_address').value,true);
    }

    function initialize() {
        if (GBrowserIsCompatible()) {
            var mapOptions = {
                center: new google.maps.LatLng(0, 0),
                zoom: 2
            };
            var divMapCanvas = $("#map-canvas")[0];
            map = new GMap2(divMapCanvas, mapOptions);
            map.setCenter(new GLatLng(37.4419, -122.1419), 2);
            map.setUIToDefault();
            geocoder = new GClientGeocoder();
        }
    }

    function showAddress(address, isDraggable) {
        if (geocoder) {
            map.clearOverlays();
            geocoder.getLatLng(
                    address,
                    function (point) {
                        if (!point) {
                            //alert(address + " not found");
                        } else {
                            map.setCenter(point, 4);
                            var marker = new GMarker(point, { draggable: isDraggable });
                            map.addOverlay(marker);
                            GEvent.addListener(marker, "dragend", function () {

                                LatLongArr = marker.getLatLng().toString().split(",")
                                LatLongArr[0] = LatLongArr[0].replace(/[() ]/g, '');
                                LatLongArr[1] = LatLongArr[1].replace(/[() ]/g, '');
                                var textbox = document.getElementsByName('lat')[0]
                                textbox.value = LatLongArr[0];
                                textbox = document.getElementsByName('long')[0]
                                textbox.value = LatLongArr[1];
                            });
                            GEvent.addListener(marker, "click", function () {

                                LatLongArr = marker.getLatLng().toString().split(",")
                                LatLongArr[0] = LatLongArr[0].replace(/[() ]/g, '');
                                LatLongArr[1] = LatLongArr[1].replace(/[() ]/g, '');
                                var textbox = document.getElementsByName('lat')[0]
                                textbox.value = LatLongArr[0];
                                textbox = document.getElementsByName('long')[0]
                                textbox.value = LatLongArr[1];
                            });
                            GEvent.trigger(marker, "click");
                        }
                    }
            );
        }
    }
</script>
{% endblock %}

helloghz/map/templates/map/videopopup.html
{% extends "map/baselayout.html" %}

{% block menubar %}
{% endblock %}

{% block body %}
<div class="video-detail-body">

<div class="row">
    <div class="col-md-12">
  
        </div></div>

<div class="row ">
    <div class="col-md-10  ">
     
        {% if returnlist %}
          


         {% for point in returnlist %}
    <div class='video-thumb'>
        <a class='video' href='http://www.youtube.com/watch?v={{point}}'><img class='img-responsive' src='http://img.youtube.com/vi/{{point}}/1.jpg'></a>
    </div>{% endfor %}
        
{% endif %}
            

        

           
    <div style="clear:both"></div>
       
    </div>
</div>
   


    </div>
{% endblock %}

{% block scripts %}

{% endblock %}

helloghz/map/templates/map/videos.html
{% extends "map/layout.html" %}{% load staticfiles %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3> Hello Videos</h3>
        </div>
    </div>

    <div class="row ">

        <div class="col-md-12">{% if fulllist %}
            <div>Total videos: {{fulllist.count}}</div>
            
            </div>{% for point in fulllist %}
            <div class='video-thumb'>
                <a class='video' href='http://www.youtube.com/watch?v={{point.vid}}'><img class='img-responsive' src='http://img.youtube.com/vi/{{point.vid}}/1.jpg'></a>
            </div>{% endfor %}

{% endif %}

        </div>


    </div>


{% endblock %}

{% block scripts %}

{% endblock %}